public enum DSA {

    /**
     * Graph
     */

    /**
     * Linked List
     */

    /**
     * Sorting
     */

    /**
     * Trees
     */

    POST_ORDER_TRAVERSAL,
    PRE_ORDER_TRAVERSAL,
    IN_ORDER_TRAVERSAL,
    TREE_SERIALIZATION,
    TREE_DESERIALIZATION,
    BOTTOM_UP_TRAVERSAL,

    /**
     * Pointers
     */
    TWO_POINTER,
    FAST_AND_SLOW_POINTER,

    /**
     * Sorting
     */
    QUICK_SORT,
    QUICK_SELECT,
    COUNT_SORT,
    HEAP_SORT,
    BUBBLE_SORT,
    MERGE_SORT,

    /**
     * Searching
     */
    BINARY_SEARCH,

    /**
     * Graph
     */
    CYCLE_DETECTION_IN_GRAPH,
    PRIMS_ALGORITHM,
    DISJOINT_SET,
    EULERIAN_CIRCUIT,

    /**
     * Segment tree
     */
    SEGMENT_TREE,

    /**
     * Shuffling
     */
    FISHER_YATES_ALGORITHM,

    /**
     * Heap
     */
    MIN_HEAP,
    MAX_HEAP,

    BIPARTITE_GRAPH,
    NUMBER_OF_CONNECTED_COMPONENTS,
    DFS_TRAVERSAL,
    TOPOLOGICAL_SORT,
    KHANS_ALGO_OF_TOPOLOGICAL_SORT,
    EULERIAN_PATH,
    KRUSKAL_ALGORITHM,
    ARTICULATION_POINT_IN_GRAPH,
    CUT_POINT_IN_GRAPH,
    BRIDGE_IN_GRAPH,
    UNION_FIND_GRAPH,
    ZERO_ONE_BFS,
    HAMILTONIAN_PATH,
    GRAPH_COLORING,
    DIRECTED_ACYCLIC_GRAPH,
    KOSARAJUS_ALGORITHM,
    TARJANS_ALGORITHM,
    SINGLE_SOURCE_SHORTEST_PATH,
    ALL_PAIR_SHORTEST_PATH,
    HAMILTONIAN_CYCLE,
    MINIMUM_SPANNING_TREE,
    BELLMAN_FORD,
    DIJKSTRA_ALGORITHM,
    FLOYD_WARSHALL,
    KNAPSACK_DYNAMIC_PROGRAMMING,
    B_TREE,
    LINKED_LIST
}
